### PR TITLE
Fix for swi 9.2.2 to 9.2.3

### PR DESCRIPTION
**Pull request by wldwrk**
Amendments to Herculog to repair after the SWI-Prolog update from 9.2.2 to 9.2.3 broke Herculog.

### CODE REVIEW

**Comment by wldwrk** [comment]
Amendments to fix Herculog after the SWI-Prolog 9.2.2 to 9.2.3 update broke Herculog.
jupyter_variable_bindings.pl - amended comments, now both SWI an SICStus will use this module
jupyter_term_handling.pl - amended the code, removed the if(swi) conditional at two places
README.md - amended some text to the current situation after the update and repair
pyproject.toml - changed the version to 0.0.10

**Comment by wldwrk** [comment]
PyPI distribution
A remark about a detail I encountered when testing to make a PyPI distribution with their TestPyPI environment.
One of the Python dependencies produced an incompatible versions error. The error: File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py" in some  lines in __init__.py. The following command fixed this error.
    pip install --upgrade twine requests-toolbelt
After this command a distribution package was successfully created, no error encoutered.
To make a distribution package I followed the tutorial at [https://packaging.python.org/en/latest/tutorials/packaging-projects/](url)

**Comment by wldwrk** [comment]
Closed this pull request. I believe with the pull request I proposed all my amendments and findings.

**Comment by dgelessus** [comment]
Thank you for the fixes! I've integrated all your changes as a combined commit 6aad8696cd1fb1cc77e94ad5d633504269ad5957 (with the version number change removed - we'll increase the version number once we make a new release). I can confirm that everything now works again with current SWI-Prolog versions.

**Comment by wldwrk** [comment]
Good to hear your confirmation and I'm happy that the fixes will find their way in a future release. Thank you very much!

**Pull request closed without merging**
